### ISSUE TITLE
Unable to start server after "Add stripe keys" commit

### ISSUE THREAD

**Issue by ddeveloperr** [ddeveloperr/full_stack_crossroads#2]
### Unable to start server after "Add stripe keys" **commit**

Try to run server:
```
rails s -p $PORT -b $IP
```

I got the following log in the rails console on the Cloud9 IDE c9.io
/usr/local/rvm/rubies/ruby-2.3.0/lib/ruby/2.3.0/psych.rb:377:in `parse': (<unknown>): did not find expected key while parsing a block mapping at line 6 column 1 (Psych::SyntaxError)
        from /usr/local/rvm/rubies/ruby-2.3.0/lib/ruby/2.3.0/psych.rb:377:in `parse_stream'
        from /usr/local/rvm/rubies/ruby-2.3.0/lib/ruby/2.3.0/psych.rb:325:in `parse'
        from /usr/local/rvm/rubies/ruby-2.3.0/lib/ruby/2.3.0/psych.rb:252:in `load'
        from /usr/local/rvm/gems/ruby-2.3.0/gems/figaro-1.0.0/lib/figaro/application.rb:60:in `parse'
        from /usr/local/rvm/gems/ruby-2.3.0/gems/figaro-1.0.0/lib/figaro/application.rb:56:in `block in raw_configuration'
        from /usr/local/rvm/gems/ruby-2.3.0/gems/figaro-1.0.0/lib/figaro/application.rb:56:in `raw_configuration'
        from /usr/local/rvm/gems/ruby-2.3.0/gems/figaro-1.0.0/lib/figaro/application.rb:64:in `global_configuration'
        from /usr/local/rvm/gems/ruby-2.3.0/gems/figaro-1.0.0/lib/figaro/application.rb:32:in `configuration'
        from /usr/local/rvm/gems/ruby-2.3.0/gems/figaro-1.0.0/lib/figaro/application.rb:42:in `each'
        from /usr/local/rvm/gems/ruby-2.3.0/gems/figaro-1.0.0/lib/figaro/application.rb:36:in `load'
        from /usr/local/rvm/gems/ruby-2.3.0/gems/figaro-1.0.0/lib/figaro.rb:23:in `load'
        from /usr/local/rvm/gems/ruby-2.3.0/gems/figaro-1.0.0/lib/figaro/rails/railtie.rb:5:in `block in <class:Railtie>'
        from /usr/local/rvm/gems/ruby-2.3.0/gems/activesupport-4.2.5/lib/active_support/lazy_load_hooks.rb:36:in `execute_hook'
        from /usr/local/rvm/gems/ruby-2.3.0/gems/activesupport-4.2.5/lib/active_support/lazy_load_hooks.rb:45:in `block in run_load_hooks'
        from /usr/local/rvm/gems/ruby-2.3.0/gems/activesupport-4.2.5/lib/active_support/lazy_load_hooks.rb:44:in `each'
        from /usr/local/rvm/gems/ruby-2.3.0/gems/activesupport-4.2.5/lib/active_support/lazy_load_hooks.rb:44:in `run_load_hooks'
        from /usr/local/rvm/gems/ruby-2.3.0/gems/railties-4.2.5/lib/rails/application.rb:148:in `run_load_hooks!'
        from /usr/local/rvm/gems/ruby-2.3.0/gems/railties-4.2.5/lib/rails/application.rb:96:in `instance'
        from /usr/local/rvm/gems/ruby-2.3.0/gems/railties-4.2.5/lib/rails/railtie.rb:123:in `config'
        from /home/ubuntu/workspace/serious-projects/full_stack_crossroads/config/application.rb:24:in `<class:Application>'
        from /home/ubuntu/workspace/serious-projects/full_stack_crossroads/config/application.rb:10:in `<module:FullStackCrossroads>'
        from /home/ubuntu/workspace/serious-projects/full_stack_crossroads/config/application.rb:9:in `<top (required)>'
        from /usr/local/rvm/gems/ruby-2.3.0/gems/railties-4.2.5/lib/rails/commands/commands_tasks.rb:78:in `require'
        from /usr/local/rvm/gems/ruby-2.3.0/gems/railties-4.2.5/lib/rails/commands/commands_tasks.rb:78:in `block in server'
        from /usr/local/rvm/gems/ruby-2.3.0/gems/railties-4.2.5/lib/rails/commands/commands_tasks.rb:75:in `tap'
        from /usr/local/rvm/gems/ruby-2.3.0/gems/railties-4.2.5/lib/rails/commands/commands_tasks.rb:75:in `server'
        from /usr/local/rvm/gems/ruby-2.3.0/gems/railties-4.2.5/lib/rails/commands/commands_tasks.rb:39:in `run_command!'
        from /usr/local/rvm/gems/ruby-2.3.0/gems/railties-4.2.5/lib/rails/commands.rb:17:in `<top (required)>'
        from /home/ubuntu/workspace/serious-projects/full_stack_crossroads/bin/rails:9:in `require'
        from /home/ubuntu/workspace/serious-projects/full_stack_crossroads/bin/rails:9:in `<top (required)>'
        from /usr/local/rvm/gems/ruby-2.3.0/gems/spring-1.6.4/lib/spring/client/rails.rb:28:in `load'
        from /usr/local/rvm/gems/ruby-2.3.0/gems/spring-1.6.4/lib/spring/client/rails.rb:28:in `call'
        from /usr/local/rvm/gems/ruby-2.3.0/gems/spring-1.6.4/lib/spring/client/command.rb:7:in `call'
        from /usr/local/rvm/gems/ruby-2.3.0/gems/spring-1.6.4/lib/spring/client.rb:28:in `run'
        from /usr/local/rvm/gems/ruby-2.3.0/gems/spring-1.6.4/bin/spring:49:in `<top (required)>'
        from /usr/local/rvm/gems/ruby-2.3.0/gems/spring-1.6.4/lib/spring/binstub.rb:11:in `load'
        from /usr/local/rvm/gems/ruby-2.3.0/gems/spring-1.6.4/lib/spring/binstub.rb:11:in `<top (required)>'
        from /home/ubuntu/workspace/serious-projects/full_stack_crossroads/bin/spring:13:in `require'
        from /home/ubuntu/workspace/serious-projects/full_stack_crossroads/bin/spring:13:in `<top (required)>'
        from bin/rails:3:in `load'
        from bin/rails:3:in `<main>'

**Comment by ddeveloperr** [comment]
:high_brightness: Bug fixed. Found which commit was ok, than update last versions stripe and figaro gems, restart app and all works as well!
